
import PrincipalMessage from "@/Components/PrincipalMessage";
import ImageSliders from "@/Components/ImageSliders";
import WelcomeBox from "@/Components/WelcomeBox";
import { mongooseConnect } from "@/lib/mongoose";
import { Slider } from "@/models/slider";

import ArticlesBox from "@/Components/ArticlesBox";

import { Article } from "@/models/article";
import Notice from "@/models/notice";
import { useState } from "react";
import NoticeModal from "@/Components/NoticeModal";
import Head from "next/head";
import AnimatedRightImage from "@/Components/AnimatedRightImage";
import MapAndMessage from "@/Components/MapAndMessage";

export default function HomePage({sliders, articles, notice}){
  const selectedArticles = articles.slice(0, 3);
  const [isModalOpen, setIsModalOpen] = useState(!!notice);

  const closeModal = () => {
    setIsModalOpen(false);
  };

  return(
    <>
    <Head>
        <title>Golden Supervision Academy</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
  
    
     <div className="flex flex-col"> 
        <ImageSliders  sliders={sliders}  />
        <WelcomeBox />
       <PrincipalMessage/>
       <div className='mt-6'>
 

   
    <ArticlesBox  articles={selectedArticles}  />
 
</div>

<div>
  <MapAndMessage />
</div>
      
      </div>
      {notice && (
        <NoticeModal isOpen={isModalOpen} closeModal={closeModal} notice={notice} />
      )}
  
    </>
  )
}

export async function getServerSideProps() {
  await mongooseConnect();
  const sliders = await Slider.find({}, null, { sort: { '_id': -1 } });
  const articles = await Article.find({}, null, { sort: { '_id': -1 } });
  const notice = await Notice.findOne({}, null, { sort: { '_id': -1 } });

  return {
    props: {
      sliders: JSON.parse(JSON.stringify(sliders)),
      articles: JSON.parse(JSON.stringify(articles)),
      notice: notice ? JSON.parse(JSON.stringify(notice)) : null,
    },
  };
}